services:

    docker-provision-verification:

        container_name: docker-provision-verification

        image: softwareshinobi/docker-provision-verification
        
        restart: no

        ports:

            - "80:80"
